add qat resource driver chart
intel/helm-charts pull request #65
Opened 2024-10-28 08:26 UTC by oxxenix

2024-10-28 09:58 UTC, eero-t requested changes

2024-10-28 09:58 UTC, eero-t commented on charts/intel-qat-resource-driver/README.md
> +> When upgrading, CRDs from previous version need to be removed manually because Helm supports neither upgrading nor deleting CRDs, see: https://github.com/helm/community/blob/main/hips/hip-0011.md
There are no CRDs, or previous version with them:
```suggestion
If you change the image tag to be used in Helm chart deployment, ensure that the version of the container image is consistent with deployment YAMLs - they might change between releases.
```

2024-10-28 09:58 UTC, eero-t commented on charts/intel-qat-resource-driver/README.md
> +
This has no CRDs:
```suggestion
```

2024-10-28 10:22 UTC, eero-t approved these changes
Looks fine to me.  @byako?

2024-10-29 06:46 UTC, byako approved these changes

2024-10-29 07:50 UTC, merged